
import { type Question, QuestionType } from '../types';

export const testQuestions: Question[] = [
  // Grammar Section
  {
    id: 1,
    type: QuestionType.GRAMMAR,
    level: 'A1',
    sectionTitle: 'Грамматика (Grammar)',
    prompt: 'I ___ a student.',
    options: ['is', 'am', 'are', 'be'],
    correctAnswer: 'am',
    points: 1,
  },
  {
    id: 2,
    type: QuestionType.GRAMMAR,
    level: 'A1',
    sectionTitle: 'Грамматика (Grammar)',
    prompt: 'She ___ to the store yesterday.',
    options: ['go', 'goes', 'went', 'gone'],
    correctAnswer: 'went',
    points: 1,
  },
  {
    id: 3,
    type: QuestionType.GRAMMAR,
    level: 'A2',
    sectionTitle: 'Грамматика (Grammar)',
    prompt: 'There aren\'t ___ apples in the fridge.',
    options: ['some', 'any', 'a', 'much'],
    correctAnswer: 'any',
    points: 2,
  },
  {
    id: 4,
    type: QuestionType.GRAMMAR,
    level: 'B1',
    sectionTitle: 'Грамматика (Grammar)',
    prompt: 'I haven\'t seen him ___ last year.',
    options: ['for', 'since', 'ago', 'from'],
    correctAnswer: 'since',
    points: 2,
  },
  {
    id: 5,
    type: QuestionType.GRAMMAR,
    level: 'B2',
    sectionTitle: 'Грамматика (Grammar)',
    prompt: 'If I ___ you, I would study harder.',
    options: ['was', 'am', 'be', 'were'],
    correctAnswer: 'were',
    points: 3,
  },
  {
    id: 6,
    type: QuestionType.GRAMMAR,
    level: 'C1',
    sectionTitle: 'Грамматика (Grammar)',
    prompt: 'Not only ___ the exam, but she also received a distinction.',
    options: ['she passed', 'did she pass', 'she has passed', 'she did pass'],
    correctAnswer: 'did she pass',
    points: 4,
  },
   {
    id: 7,
    type: QuestionType.GRAMMAR,
    level: 'C2',
    sectionTitle: 'Грамматика (Grammar)',
    prompt: '___ I to have known you were coming, I would have baked a cake.',
    options: ['If', 'Should', 'Had', 'Would'],
    correctAnswer: 'Had',
    points: 5,
  },
  // Vocabulary Section
  {
    id: 8,
    type: QuestionType.VOCABULARY,
    level: 'A1',
    sectionTitle: 'Словарный запас (Vocabulary)',
    prompt: 'What is the opposite of "happy"?',
    options: ['Joyful', 'Angry', 'Sad', 'Excited'],
    correctAnswer: 'Sad',
    points: 1,
  },
  {
    id: 9,
    type: QuestionType.VOCABULARY,
    level: 'A2',
    sectionTitle: 'Словарный запас (Vocabulary)',
    prompt: 'A person who designs buildings is called an ___.',
    options: ['artist', 'engineer', 'architect', 'doctor'],
    correctAnswer: 'architect',
    points: 2,
  },
  {
    id: 10,
    type: QuestionType.VOCABULARY,
    level: 'B1',
    sectionTitle: 'Словарный запас (Vocabulary)',
    prompt: 'He decided to ___ smoking after his doctor\'s advice.',
    options: ['give up', 'give in', 'give away', 'give back'],
    correctAnswer: 'give up',
    points: 2,
  },
  {
    id: 11,
    type: QuestionType.VOCABULARY,
    level: 'B2',
    sectionTitle: 'Словарный запас (Vocabulary)',
    prompt: 'The word "ubiquitous" means:',
    options: ['rare', 'present everywhere', 'very beautiful', 'difficult to understand'],
    correctAnswer: 'present everywhere',
    points: 3,
  },
    {
    id: 12,
    type: QuestionType.VOCABULARY,
    level: 'C1',
    sectionTitle: 'Словарный запас (Vocabulary)',
    prompt: 'Her speech was full of ___ remarks, which made everyone laugh.',
    options: ['witty', 'somber', 'mundane', 'vague'],
    correctAnswer: 'witty',
    points: 4,
  },
  // Reading Section
  {
    id: 13,
    type: QuestionType.READING,
    level: 'A2',
    sectionTitle: 'Чтение (Reading)',
    prompt: 'Прочитайте текст и ответьте на вопрос. \n\n The Eiffel Tower is a famous landmark in Paris, France. It was built between 1887 and 1889. It is made of iron and is 330 meters tall. Millions of tourists visit it every year to enjoy the stunning views of the city from its observation decks. \n\n Where is the Eiffel Tower located?',
    options: ['London', 'New York', 'Paris', 'Rome'],
    correctAnswer: 'Paris',
    points: 2,
  },
  {
    id: 14,
    type: QuestionType.READING,
    level: 'B2',
    sectionTitle: 'Чтение (Reading)',
    prompt: 'Прочитайте текст и ответьте на вопрос. \n\n The phenomenon of "urban heat islands" refers to the fact that metropolitan areas are significantly warmer than their surrounding rural areas. This is primarily caused by human activities. Materials like concrete and asphalt, common in cities, absorb and retain more of the sun\'s heat than natural landscapes. Additionally, waste heat from buildings, industrial facilities, and vehicles contributes to the higher temperatures. This effect can have serious consequences, including increased energy consumption for cooling and negative impacts on public health. \n\n According to the text, what is the MAIN reason for urban heat islands?',
    options: ['Lack of green spaces', 'The materials used in city construction and waste heat', 'Global warming', 'The density of the population'],
    correctAnswer: 'The materials used in city construction and waste heat',
    points: 3,
  },
    {
    id: 15,
    type: QuestionType.READING,
    level: 'C1',
    sectionTitle: 'Чтение (Reading)',
    prompt: 'Прочитайте текст и ответьте на вопрос. \n\n The Sapir-Whorf hypothesis posits that the structure of a language affects its speakers\' worldview or cognition. The strong version, linguistic determinism, claims that language dictates thought and that linguistic categories limit and determine cognitive categories. The weaker version, linguistic relativity, argues that linguistic categories and usage only influence thought and decisions. While the strong version is now largely discredited, the idea that language can shape our perception of reality continues to be a subject of academic debate and research. \n\n What is the primary difference between the strong and weak versions of the Sapir-Whorf hypothesis?',
    options: ['One is about vocabulary, the other is about grammar.', 'The strong version claims language controls thought, while the weak version says it only influences it.', 'The strong version has been proven, while the weak version is hypothetical.', 'There is no significant difference.'],
    correctAnswer: 'The strong version claims language controls thought, while the weak version says it only influences it.',
    points: 4,
  },
  // Listening Section
  {
    id: 16,
    type: QuestionType.LISTENING,
    level: 'A2',
    sectionTitle: 'Аудирование (Listening)',
    prompt: 'Прослушайте аудио и ответьте на вопрос. What time does the train to Manchester leave?',
    listeningText: 'The train to Manchester will depart from platform 4 at 10:30 AM.',
    options: ['10:30 AM', '4:00 PM', 'Platform 4', 'Manchester'],
    correctAnswer: '10:30 AM',
    points: 3,
  },
    {
    id: 17,
    type: QuestionType.LISTENING,
    level: 'B2',
    sectionTitle: 'Аудирование (Listening)',
    prompt: 'Прослушайте аудио и ответьте на вопрос. What did the speaker forget to buy?',
    listeningText: 'Right, I\'ve got the milk, eggs, and bread. I knew I was forgetting something. Oh, I completely forgot about the coffee. I\'ll have to go back for it later.',
    options: ['Milk', 'Eggs', 'Bread', 'Coffee'],
    correctAnswer: 'Coffee',
    points: 3,
  },
    {
    id: 18,
    type: QuestionType.LISTENING,
    level: 'C1',
    sectionTitle: 'Аудирование (Listening)',
    prompt: 'Прослушайте аудио и ответьте на вопрос. What is the speaker\'s attitude towards the new policy?',
    listeningText: 'While I can see the theoretical benefits of the new work-from-home policy, I have some serious reservations about its practical implementation. The potential for a decline in team cohesion is not something to be taken lightly.',
    options: ['Fully supportive', 'Completely opposed', 'Skeptical and concerned', 'Indifferent'],
    correctAnswer: 'Skeptical and concerned',
    points: 4,
  },
  // Writing Section
  {
    id: 19,
    type: QuestionType.WRITING,
    level: 'B1',
    sectionTitle: 'Письмо (Writing)',
    prompt: 'Напишите небольшой абзац (50-80 слов) на одну из тем: \n 1. Опишите свой последний отпуск. \n 2. Обсудите плюсы и минусы жизни в большом городе. \n (This will be graded manually)',
    points: 5, // Manual grading
  },
    {
    id: 20,
    type: QuestionType.WRITING,
    level: 'C1',
    sectionTitle: 'Письмо (Writing)',
    prompt: 'Напишите короткое эссе (100-150 слов) на одну из тем: \n 1. "Technology has made communication better." Do you agree or disagree? \n 2. What is the most effective way to learn a new language? \n (This will be graded manually)',
    points: 8, // Manual grading
  },
  // Speaking Section
  {
    id: 21,
    type: QuestionType.SPEAKING,
    level: 'B1',
    sectionTitle: 'Говорение (Speaking)',
    prompt: 'Запишите свой устный ответ на следующие вопросы: \n 1. Please read this sentence aloud: "The quick brown fox jumps over the lazy dog." \n 2. What is your favorite hobby and why? \n (This will be graded manually)',
    points: 5, // Manual grading
  },
    {
    id: 22,
    type: QuestionType.SPEAKING,
    level: 'C1',
    sectionTitle: 'Говорение (Speaking)',
    prompt: 'Запишите свой устный ответ на следующие вопросы: \n 1. Describe a challenge you have faced and how you overcame it. \n 2. What, in your opinion, is the biggest issue facing the world today? \n (This will be graded manually)',
    points: 8, // Manual grading
  },
];
